// Client-side PDF report generation (jsPDF). Produces a shareable decision
// report including the plain-language reasons and the blockchain proof.

"use client";

import { jsPDF } from "jspdf";
import type { ClaimRecord } from "./types";
import { formatDateTime, formatINR } from "./utils";

export function downloadReport(claim: ClaimRecord): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const line = (gap = 16) => (y += gap);
  const text = (s: string, size = 11, bold = false, color: [number, number, number] = [15, 37, 64]) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(s, maxWidth);
    doc.text(lines, margin, y);
    y += lines.length * (size + 4);
  };

  // Header band
  doc.setFillColor(21, 101, 192);
  doc.rect(0, 0, pageWidth, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("We-WhoCares", margin, 38);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Explainable AI Claim Decision — Immutable Audit Trail on Monad", margin, 54);
  y = 100;

  const { decision, input, proof } = claim;

  text(`Decision: ${decision.decision}`, 16, true, decision.decision === "REJECT" ? [200, 30, 30] : [15, 120, 70]);
  text(`Claim ID: ${claim.id}    |    Confidence: ${decision.confidence}%`, 10, false, [90, 100, 115]);
  text(`Recorded: ${formatDateTime(claim.createdAt)}`, 10, false, [90, 100, 115]);
  line(8);

  text("Summary of Inputs", 12, true);
  text(`ABHA: ${maskAbha(input.abhaNumber)}`);
  text(`Scheme: ${input.scheme === "PM-JAY" ? "PM-JAY (Ayushman Bharat)" : "Private insurance"}`);
  text(`Policy Number: ${input.policyNumber || "-"}`);
  text(`Procedure (claimed): ${input.procedure}`);
  text(`Claimed Amount: ${formatINR(input.claimedAmount)}    |    Coverage Limit: ${formatINR(input.policy.coverageLimit)}`);
  text(`Procedure Performed: ${input.hospitalRecord.procedurePerformed}`);
  text(`Pre-Authorisation Provided: ${input.hospitalRecord.preAuthorizationProvided ? "Yes" : "No"}`);
  if (input.fileNames.length) text(`Documents: ${input.fileNames.join(", ")}`);
  line(8);

  text("Rule-by-rule evaluation", 12, true);
  decision.ruleResults.forEach((r) => text(`${r.id}. ${r.rule}: ${r.status} — ${r.detail}`, 10));
  line(6);

  text("Why this decision?", 12, true);
  decision.reasons.forEach((r, i) => text(`${i + 1}. ${r}`, 11));
  line(4);
  if (decision.explanation) text(decision.explanation, 10, false, [70, 80, 95]);
  line(10);

  text("Blockchain Proof", 12, true);
  if (proof) {
    text(`Network: Monad Testnet (chainId ${proof.chainId})`, 10);
    text(`Contract: ${proof.contractAddress}`, 10);
    text(`Transaction: ${proof.txHash}`, 10);
    text(`Reasons Hash (keccak256): ${proof.reasonsHash}`, 10);
    if (proof.blockNumber !== undefined) text(`Block: #${proof.blockNumber}`, 10);
    text(`Explorer: ${proof.explorerUrl}`, 9, false, [21, 101, 192]);
    if (proof.simulated) text("Note: demo mode — simulated on-chain hash.", 9, false, [180, 120, 0]);
  } else {
    text("No blockchain proof recorded.", 10, false, [150, 60, 60]);
  }
  line(14);

  text(
    "Privacy: full health data (ABHA, records, reasons) stays off-chain; only the keccak256 commitment above is on Monad. This decision is committed on-chain and cannot be altered - anyone can re-hash the published reasons and verify the match. Generated by We-WhoCares.",
    9,
    false,
    [120, 130, 145],
  );

  doc.save(`${claim.id}-we-whocares-report.pdf`);
}

function maskAbha(abha: string): string {
  const digits = abha.replace(/\D/g, "");
  if (digits.length < 4) return abha || "-";
  return `**-****-****-${digits.slice(-4)}`;
}
